# Site settings
title: Writeups and stuff

authors:
  - username: 0xAWES0ME
    github: true
    twitter: false
  - email: jgeralnik@gmail.com
    username: jgeralnik
    github: true
    twitter: true
  - email: matan@matan.me
    username: mtnmts
    github: true
    twitter: false

description: "CTF writeups from team 0xAWES0ME"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3

comments: true