# Site settings
title: Writeups and stuff
email: jgeralnik@gmail.com
username: jgeralnik
description: "CTF writeups from team 0xAWES0ME"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
