# Site settings
title: Writeups and stuff
email: jgeralnik@gmail.com
username: jgeralnik
description: "Contains stuff I write, including at least one writeup from at least one ctf"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
